### ISSUE TITLE
SchemaRepository behaves erratically under concurrent access

### ISSUE THREAD

**Issue by akleiman** [eclipse-vertx/vertx-json-schema#101]
### Version

4.3.1, 4.4.1, etc.

### Context

I've run into a problem with SchemaRepository that seems to stem from concurrent access to the repository. Having a look at the code I think it could be fixed by changing the `lookup` map to a `ConcurrentHashMap` rather than a simple `HashMap`.

My production case is: I have many different schemas stored in a database. The application is a message-processor; it receives a message, reads the schema from the database (in text format) and validates them using the Validator. Often, near application startup we see exceptions that don't make much sense, such as a call to `dereference`  followed immediately by a call to `validator`  with that same key throws `Exception in thread "Main" java.lang.IllegalArgumentException: Unknown $ref: propName_2`

### Do you have a reproducer?

https://github.com/akleiman/vertx-jsonvalidator-concurrency-reproducer
run with `gradle run`, it was built on Java 20. the first lines of the output are what I see in my production code. In production I'm not using virtual threads in my production code, I used it in the reproducer for simplicity and so I could spawn many different threads at once.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

### Steps to reproduce

1. Set up a SchemaRepository to be used concurrently
2. On multiple threads/executors:
3. Load a schema (only tested by loading from a string)
4.Dereference the schema
5. Obtain the validator
6. Some of the calls to `validator`  will fail, as if it didn't know the URL that was just registered in dereference.

### Extra

Java 17 and 20.

**Comment by akleiman** [comment]
Ran some further tests, replacing the `HashMap` with a `ConcurrentHashMap` in vertx-json-schema and I no longer see errors in my reproducer.

**Comment by tsegismont** [comment]
@pk-work any idea about this one?

**Comment by pk-work** [comment]
I have not yet debugged the reproducer (due to the lack of Java 20) but that's interesting. Because my understanding is that once a schema is dereferenced, the entries in the lookup Map shouldn't change.

I will try to have a look into it the next days. But if a ConcurrentHashMap solves the issue, we can change it. The only issue I could imagine is that we have a performance loss due to the ConcurrentHashMap.
