### ISSUE TITLE
Json schema does not support formats for Integer or Number types

### ISSUE THREAD

**Issue by CheesyBoy123** [eclipse-vertx/vertx-json-schema#124]
#### Describe the feature

There are some formats that are checked for Strings via Format.fastFormat. It would be nice to have formats as well for "intenger" and "number" types.

ex:
type: integer, format int32
type: integer, format int64
type: number, format float
type: number, format double

This is currently causing issue in vertx-openapi (https://github.com/eclipse-vertx/vertx-openapi/issues/53) where OpenAPI spec allows for integer and number's formats to be checked.

#### Use cases

Various integer and number formats checking will be available for json schema validation (would be useful for closing the above issue vertx-openapi)

#### Contribution

I am more than happy to contribute.

**Comment by pk-work** [comment]
Merged with https://github.com/eclipse-vertx/vertx-json-schema/pull/128
