### ISSUE TITLE
Garbled error message for enums

### ISSUE THREAD

**Issue by therockstorm** [eclipse-vertx/vertx-json-schema#22]
Get the following error,

`Provided value don't match pattern, Input doesn't match one of allowed values of enum: [Ljava.lang.Object;@470aedb8]`. Our enum in the OpenAPI spec is `enum: [file]`.

### Version

4.0.0.CR1

### Steps to reproduce

Pass an incorrect enum value

**Comment by slinkydeveloper** [comment]
@therockstorm PR https://github.com/eclipse-vertx/vertx-json-schema/pull/23, can you review it?

**Comment by therockstorm** [comment]
Approved, thanks for the fast turnaround!
