### ISSUE TITLE
Validator fails against propertyName field

### ISSUE THREAD

**Issue by EmmaHumber** [eclipse-vertx/vertx-json-schema#28]
### Version

        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-json-schema</artifactId>
            <version>4.0.0</version>
        </dependency>

### Context
I'm attempting to validate an asyncApi json object, against the asyncApi schema using schema.validateAsync (validateSync fails too)

The AsyncAPI schema is here https://raw.githubusercontent.com/asyncapi/asyncapi/master/versions/2.0.0/schema.json

When validateAsync gets to checking the propertyNames in my json object, I get the following exception:

```
input don't match any of types [STRING]
ValidationException{message='input don't match any of types [STRING]', keyword='type', input={"topic":{"subscribe":{"message":{"payload":{"type":"string"}}}}}, schema=io.vertx.json.schema.common.SchemaImpl@5bdad412, scope=urn:vertxschemas:05718eb8-d4ff-4d36-92ce-7649ce0e5014#}
	at io.vertx.json.schema.ValidationException.createException(ValidationException.java:54)
	at io.vertx.json.schema.draft7.TypeValidatorFactory$TypeValidator.validateSync(TypeValidatorFactory.java:92)
	at io.vertx.json.schema.common.SchemaImpl.runSyncValidator(SchemaImpl.java:200)
```

### Do you have a reproducer?

I've shrunk down the schema and json to a small recreate:

specDefinition:
```
{
  "title": "AsyncAPI 2.0.0 schema.",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "channels": {
      "type": "object",
      "propertyNames": {
        "type": "string"  -> swap this to be object and it works fine in vertx, but fails for other validators
      }
    }
  }
}
```

jsonData:
```
{
  "channels": {
    "topic": {
      "subscribe": {
          "message": {
            "payload": {
              "type": "string"
            }
          }
        }
      }
  }
}
```
The above object and spec validates OK in eg https://www.liquid-technologies.com/online-json-schema-validator or using a different Java json schema validator.

### Steps to reproduce

SchemaRouter schemaRouter = SchemaRouter.create(vertx, new SchemaRouterOptions());
SchemaParser schemaParser = Draft7SchemaParser.create(schemaRouter);
            
//specDefinition + jsonData - Files read in using vertx.fileSystem().readFile

Schema schema = schemaParser.parse(specDefinition.toJsonObject());
schema.validateAsync(jsonData.toJsonObject()).onFailure(error -> {
                        error.printStackTrace();
                    });

### Extra

When the validator iterates through the valid SchemaTypes here

https://github.com/eclipse-vertx/vertx-json-schema/blob/10256d3e1f5914c887aeedd500de990d64d0918a/src/main/java/io/vertx/json/schema/draft7/TypeValidatorFactory.java#L91 

I think that only a String is a valid type but the json being checked is of type object - {"topic":{"subscribe":{"message":{"payload":{"type":"string"}}}}}

propertyNames should validate the fields within the json object, not the whole object.

**Comment by slinkydeveloper** [comment]
Wanna check out the fix? https://github.com/eclipse-vertx/vertx-json-schema/pull/29

I'm actually a bit surprised how a small bug like that wasn't catched up by the tck.

**Comment by EmmaHumber** [comment]
Thanks for the quick fix - I'll give the change a try shortly

**Comment by EmmaHumber** [comment]
Verified - works as expected :)

Thanks again!
