### ISSUE TITLE
2020-02 Support

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-json-schema#43]
In order to support the latest openAPI (the migration guide) mentions 2020-02

https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

**Comment by slinkydeveloper** [comment]
Now it even mentions 2020-12 https://spec.openapis.org/oas/v3.1.0#schema-object

**Comment by philsturgeon** [comment]
Hello! As the maintainer of [openapi.tools](https://openapi.tools), and as somebody works with Linux Foundation helping out in OpenAPI-land, I'm reaching out to tooling vendors to track the progress towards supporting OpenAPI v3.1, to see what roadblocks there are beyond folks just generally being busy at this ridiculous time.

OpenAPI v3.1 has a bunch of great little changes, solving problems like the [JSON Schema <!=> OpenAPI Schema Object divergence](https://apisyouwonthate.com/blog/openapi-json-schema-divergence). It also fixes some other inconsistencies and duplicate ways of doing things. It's the best version and everyone should be using it, but we need tooling to catch up. Just in case folks didn't notice, or don't have resources to simplify the process, I'm here to give a friendly prod and send over some handy links.

Here are a few articles showing off the differences between OpenAPI v3.0 and v3.1.

- https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0
- https://www.apimatic.io/blog/2021/09/migrating-to-and-from-openapi-3-1/ 
- https://nordicapis.com/whats-new-in-openapi-3-1-0/

Here are some example files which can make for handy pass/fail test cases:

https://github.com/Mermade/openapi3-examples/tree/master/3.1 

If you're looking for the JSON Schema that defines a valid OpenAPI document, that'll be right over here: 

https://github.com/OAI/OpenAPI-Specification/tree/main/schemas/v3.1 


LMK if you have any questions!

**Comment by pmlopes** [comment]
@philsturgeon thank you for your message. In the latest release 4.3.1 we have implemented most of the JSON Schema 2020-12 support. So in terms of jsonschema we're on the good track. The next step is to update the current OpenAPI code in vertx web (which allows bootstrapping a router from a openapi document) up to date to 3.1.

Your link to a short set of examples to verify the new api are really welcome!

**Comment by mohamnag** [comment]
seems like since 4.3 this is done but the issue is still open, right?

**Comment by pmlopes** [comment]
Yes in terms of JSON schema we are in good shape, regarding openapi we are close to deliver 3.1 support. We could close the issue here.

**Comment by pmlopes** [comment]
we have already good support for 2020-12 (TCK can attest this). The main issue is that we aren't addressing $dynamicRef/Anchor yet and this prevents us to validate meta schemas.

There's an issue for this problem and I'll close this one as we can already validate objects "assuming" that the provided schema is well formed.
