### ISSUE TITLE
Concurrent Modification Exceptions with many schemas (has reproducer)

### ISSUE THREAD

**Issue by scardwell15** [eclipse-vertx/vertx-json-schema#46]
### Version
4.1.2

### Context
ConcurrentModificationExceptions occur often with many schemas loaded. This is probably the same ConcurrentModificationException seen in the earlier issue.

Note that removing most schemas except ChfInfoList (which had the NullPointerExceptions in the earlier ticket, but does not reproduce here) and LmfInfo (which has most of the ConcurrentModificationExceptions) and the schemas they depend on will fix this issue.

### Do you have a reproducer?

https://github.com/scardwell15/vertx-schema-tester

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. Load many schemas in tests and try to assert validations.
2. Notice concurrent modification exceptions in vertx-json-schema, mostly in LmfInfoNGTest. 

### Extra

java 11 on feren OS

**Comment by pmlopes** [comment]
That API has been deprecated in favour of the new API.
