### ISSUE TITLE
Needs better documentation on how to use

### ISSUE THREAD

**Issue by asad-awadia** [eclipse-vertx/vertx-json-schema#47]
The current readme is insufficient on providing enough context on how to use this lib

Needs more documentation and examples

**Comment by tsegismont** [comment]
The documentation is available online https://vertx.io/docs/vertx-json-schema/java/

I will update the `README` file to make it look like those of the other Vert.x projects.

**Comment by asad-awadia** [comment]
@tsegismont that documentation isn't helpful either

needs better examples/guides

**Comment by tsegismont** [comment]
@slinkydeveloper have you planned to write an how-to?

@asad-awadia you need to be more specific about what information you're missing. In the meantime, perhaps you can have a look at test code?
