### ISSUE TITLE
JsonObjectSchema.resolve() does not resolve JsonArray

### ISSUE THREAD

**Issue by dprincethg** [eclipse-vertx/vertx-json-schema#58]
### Questions

The JsonObjectSchema.resolve() **only** resolves References inside  Jsonbject.

However, JsonArray may also contains reference(s).

Like for example, "Parameters" Field in OpenAPI: https://spec.openapis.org/oas/latest.html#operation-object

`
"parameters":[{"$ref":"#/components/parameters-query/aQeueryKey"}]
`

### Version

v 4.3.0

### Do you have a reproducer?

No

### Steps to reproduce

1. Create JsonSchema instance from JsonObject containning arrays of Refs
2. Call jsonSchema.resolve();
3. Refs inside Arrays are not resolved
4.

**Comment by pmlopes** [comment]
The PR above will address this issue, The PR is not complete yet. The final goal is to add support to resolve and validate from a repository using just a json pointer, no need to keep a distinction between start schema and lookup schemas when using a repository.

**Comment by dprincethg** [comment]
Nice , it seems more efficient to add schema(s) to the repository (directly or from full openAPI content).
And then to get Validator from jsonPointer to (sub) schema.

**Comment by pmlopes** [comment]
Indeed, I think that is should add all schemas to a repository and later we can always perform a resolution or validation by json pointer reference

https://github.com/eclipse-vertx/vertx-json-schema/pull/60
