### ISSUE TITLE
oneOf validation exception provides no help about wrong schema

### ISSUE THREAD

**Issue by matter-it-does** [eclipse-vertx/vertx-json-schema#66]
### Version

Which version(s) did you encounter this bug ?
4.2.5
### Context
The exception message has only this 
```
[Bad Request] Validation error for body application/json: No schema matches
```

while other schema errors tell you what is missing, or what keyword is not being followed.

**Comment by pigbayspy** [comment]
**No schema matches** means there is no required field

**Comment by pmlopes** [comment]
Please use the new API and for json schema use the `checkValidity()` method on the `OutputUnit`.
