### ISSUE TITLE
Support data retrieval from JSON schema repositories

### ISSUE THREAD

**Issue by Markus-Elfring** [eclipse-vertx/vertx-json-schema#69]
Some data can be stored also in [schema repositories](https://github.com/eclipse-vertx/vertx-json-schema/blob/2b9f2294af078787511c3da2824e90c6e7fb3551/src/main/java/io/vertx/json/schema/SchemaRepository.java#L19 "Update candidate").
:eyes: I am looking for ways to retrieve selected schema information from this storage system.
:crystal_ball: Which programming interfaces will support such functionality?

**Comment by pmlopes** [comment]
You can use the `find()` method or the resolve. Find will perform a complex lookup based on a json pointer. `resolve()` can look up a exact schema.
