### ISSUE TITLE
Support data validation based on parameter “JSON schema identification”

### ISSUE THREAD

**Issue by Markus-Elfring** [eclipse-vertx/vertx-json-schema#70]
[The programming interface “Vert.x SchemaRepository”](https://github.com/eclipse-vertx/vertx-json-schema/blob/2b9f2294af078787511c3da2824e90c6e7fb3551/src/main/java/io/vertx/json/schema/SchemaRepository.java#L60 "Update candidate") supports a few validation functions.
:thought_balloon: I would like to be able to identify the desired start validation schema by [the standard property “`$id`”](https://github.com/json-schema-org/understanding-json-schema/blob/973fac0788131779dda0144664bbb81fced13595/source/basics.rst#user-content-declaring-a-unique-identifier "Declaring an unique schema identifier").
:crystal_ball: How will the chances evolve to add corresponding functions?

**Comment by pmlopes** [comment]
This is now possible with the new API, you can use a reference for a already dereferenced schema
