### ISSUE TITLE
Fix inefficient use of keySet iterator instead of entrySet iterator

### ISSUE THREAD

**Issue by Markus-Elfring** [eclipse-vertx/vertx-json-schema#73]
### Version
4.3.4

### Context
The code analysis tool “SpotBugs 4.7.3” pointed the following information out for [further development considerations according to the implementation of the methods “validateAsync” and “validateSync” within the class “PropertiesValidator”](https://github.com/eclipse-vertx/vertx-json-schema/blob/cf15e1d2a3546af80844d05babfbff6039f33724/src/main/java/io/vertx/json/schema/common/PropertiesValidatorFactory.java#L152 "Update candidate").

:thought_balloon: [Inefficient use of keySet iterator instead of entrySet iterator](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#wmi-inefficient-use-of-keyset-iterator-instead-of-entryset-iterator-wmi-wrong-map-iterator "Bug description")

**Comment by pmlopes** [comment]
We have deprecated this API and the new one does not uses this code.
